import { useEffect, useState } from 'react';
import type { RelationType, SearchHit } from './types';

const relationTypes: RelationType[] = ['requires', 'uses', 'extends', 'supersedes', 'conflicts_with', 'related_to', 'produces', 'consumes'];

export function ManualRelationDialog({ sourceSkillId, searchSkills, onCreate, onClose }: { sourceSkillId: string; searchSkills: (query: string) => Promise<SearchHit[]>; onCreate: (input: { sourceSkillId: string; targetSkillId: string; relationType: RelationType; constraint: string | null }) => Promise<void>; onClose: () => void }) {
  const [query, setQuery] = useState(''); const [results, setResults] = useState<SearchHit[]>([]); const [target, setTarget] = useState<SearchHit>(); const [relationType, setRelationType] = useState<RelationType>('uses'); const [constraint, setConstraint] = useState(''); const [busy, setBusy] = useState(false);
  useEffect(() => { if (!query.trim()) { setResults([]); return; } const timer = window.setTimeout(() => { void searchSkills(query).then(setResults).catch(() => setResults([])); }, 220); return () => window.clearTimeout(timer); }, [query, searchSkills]);
  return <div className="modal" role="dialog" aria-modal="true" aria-label="Create relation proposal"><div className="modal-card"><header><h2>Add relation</h2><button onClick={onClose}>Close</button></header><p>Source: <code>{sourceSkillId}</code></p><label>Target search<input aria-label="Relation target search" value={query} onChange={(event) => { setQuery(event.target.value); setTarget(undefined); }} placeholder="Search skill name or logical key" /></label>{results.length > 0 && <ul className="search-results">{results.map((item) => <li key={item.id}><button onClick={() => { setTarget(item); setQuery(item.name); setResults([]); }}>{item.name}<small>{item.logicalKey ?? item.summary ?? item.id} · {item.version ? `v${item.version}` : item.id}</small></button></li>)}</ul>}<p>Target: {target ? `${target.name} (${target.id})` : 'not selected'}</p><label>Relation<select aria-label="Manual relation type" value={relationType} onChange={(event) => setRelationType(event.target.value as RelationType)}>{relationTypes.map((item) => <option key={item} value={item}>{item}</option>)}</select></label><label>Constraint<input aria-label="Manual relation constraint" value={constraint} onChange={(event) => setConstraint(event.target.value)} placeholder="optional, e.g. >=3" /></label><button disabled={!target || busy} onClick={() => { if (!target) return; setBusy(true); void onCreate({ sourceSkillId, targetSkillId: target.id, relationType, constraint: constraint || null }).finally(() => setBusy(false)); }}>Create proposal</button></div></div>;
}
