export type RelationType='requires'|'uses'|'extends'|'supersedes'|'conflicts_with'|'related_to'|'produces'|'consumes';
export interface GraphNode { id:string;skillId:string;version:number;name:string;kind:'skill'|'tool';logicalKey:string;lifecycle:string;totalSize:number;resources:Array<{relativePath:string;mode:number;mime:string;size:number;sha256:string}>;bodySha256:string;createdAt?:string;updatedAt?:string;metadata?:Record<string,unknown>;owner?:string;scope?:{ownerUserId:string;agentId:string};history?:number[];selection?:{reason:string;score?:number;tier?:string;depth?:number}; }
export interface GraphEdge {source:string;sourceVersion:number;type:RelationType;target:string;targetVersion:number;constraint:string|null;direction:string;reason?:string}
export interface GraphData {root?:{id:string;version:number};nodes:GraphNode[];edges:GraphEdge[];metadata:{nodes:number;edges:number;truncated:boolean;truncatedNodes:number;truncatedEdges:number;limits:{maxDepth:number;maxNodes:number;maxEdges:number};generatedAt:string;includeHistory:boolean};mode?:string}
export interface SearchHit extends GraphNode {summary?:string}
export interface SkillDetail extends GraphNode {body?:string;summary?:string;scope?:{ownerUserId:string;agentId:string}}
export interface ResourceMeta {relativePath:string;mode:number;mime:string;size:number;sha256:string}
export interface RetrievalSummary {requestId:string;profile:string;createdAt:string;noMatch:boolean;redactedQuery?:string;classification:{primary:string;labels:string[]};counts:{candidates:number;selectedSkills:number;selectedMemories:number;graphExpansions:number}}
export type ProposalStatus='proposed'|'approved'|'rejected'|'stale'|'superseded';
export type ProposalLayer='canonical'|'proposed'|'both';
export type ProposalDomain='operational'|'semantic'|'both';
export interface ProposalRenderEdge { proposalId:string; sourceSkillId:string; sourceVersion:number; targetSkillId:string; targetVersion:number; relationType:RelationType; targetVersionConstraint:string|null; confidence:number; detector:string; status:ProposalStatus; }
export interface Filters { relations:Set<RelationType>;lifecycle:string;query:string;owner?:string;scope?:string;tag?:string;profile?:string;kind?:'all'|'skill'|'tool';isolatedOnly?:boolean;proposalLayer?:ProposalLayer;proposalStatuses?:Set<ProposalStatus>;proposalDetectors?:Set<string>;proposalMinConfidence?:number;proposalDomain?:ProposalDomain;}
export interface RelationProposal { id:string;scope?:{ownerUserId:string;agentId:string};sourceSkillId:string;sourceVersion:number;targetSkillId:string;targetVersionSnapshot:number;relationType:RelationType;targetVersionConstraint:string|null;reviewedRelationType?:RelationType|null;reviewedSourceSkillId?:string|null;reviewedTargetSkillId?:string|null;reviewedConstraint?:string|null;reviewedConstraintSet?:boolean;reviewModified?:boolean;origin?:'discovered'|'manual';candidateScore?:number|null;confidence:number;detector:string;detectorVersion?:string;model?:string;reason:string;status:ProposalStatus;evidence:Array<{kind:string;excerpt?:string;score?:number;source?:string;sourceVersion?:number;startOffset?:number;endOffset?:number;targetMentionOffset?:number}>;createdAt:string;reviewedAt?:string;reviewedBy?:string;rejectionReason?:string }
export type ExplicitCandidateStatus='READY_FOR_REVIEW'|'ALREADY_STAGED'|'ALREADY_CANONICAL'|'UNRESOLVED'|'AMBIGUOUS';
export interface ExplicitCandidate { pairKey:string;sourceSkillId:string;sourceLogicalKey:string;sourceVersion:number;targetSkillId:string|null;targetLogicalKey:string|null;targetVersion:number|null;relationType:RelationType;sourceDeclaresTarget:boolean;targetDeclaredSource:boolean;reciprocal:boolean;status:ExplicitCandidateStatus;activeProposalIds:string[];canonicalRelationId:string|null;evidence:{metadataField:string;sourceDeclaredTarget:boolean;targetDeclaredSource:boolean;reciprocal:boolean};unresolvedToken?:string; }
export interface ExplicitCandidateSummary { total:number;ready:number;readyReciprocal:number;readyOneWay:number;alreadyCanonical:number;alreadyStaged:number;unresolved:number;ambiguous:number; }
export interface ExplicitImpact { selected:number;current:{edges:number;components:number;isolated:number;largest:number};afterIfApplied:{edges:number;components:number;isolated:number;largest:number};newEdges:number; }
