import { randomUUID, createHash } from 'node:crypto';
import { HubError } from '../errors.js';
import { canonicalDigest, logicalKey, catalogSyncDigest, safeRelativeLocator, normalizeRootDescriptors, rootBindingsFingerprint } from './logical-key.js';
import { sanitizeMetadata, boundedSummary } from './sanitization.js';
import type { CatalogOperation, CatalogScanner, SyncInput, SyncPreview, CatalogCandidate } from './types.js';
import type { CatalogRepository, CatalogSyncRepository } from './contracts.js';
import type { MutationMeta } from '../storage/contracts.js';
import { candidatesFrom } from './source-scanner.js';

type Deps={catalog?:CatalogRepository; sync?:CatalogSyncRepository; profileFingerprint?:(profile:string)=>string; targetFingerprint?:(input:SyncInput)=>string; afterMarker?:()=>void};
export type MarkerPort={snapshot:()=>{existed:boolean;bytes?:Buffer}; write:(bytes:Buffer)=>void; restore:(prior:{existed:boolean;bytes?:Buffer})=>void};
const digestBytes=(bytes:Buffer)=>createHash('sha256').update(bytes).digest('hex');
const safeMeta=(c:CatalogOperation['candidate'])=>c?{kind:c.kind,rootId:c.rootId??'default',relativePath:c.relativePath,locator:safeRelativeLocator(c.locator),sourceKind:c.sourceKind,bytes:Buffer.alloc(0),contentDigest:c.contentDigest??digestBytes(c.bytes),metadata:sanitizeMetadata(c.metadata??{}),summary:boundedSummary(c.summary)}:undefined;
const descriptor=(c:CatalogCandidate)=>({kind:c.kind,rootId:c.rootId??'default',relativePath:c.relativePath,locator:safeRelativeLocator(c.locator),sourceKind:c.sourceKind??c.kind,metadata:sanitizeMetadata(c.metadata??{}),summary:boundedSummary(c.summary),contentDigest:c.contentDigest??digestBytes(c.bytes)});
const opDescriptor=(o:CatalogOperation)=>{const out:Record<string,unknown>={action:o.action,logicalKey:o.logicalKey};if(o.expectedVersion!==undefined)out.expectedVersion=o.expectedVersion;if(o.reason!==undefined)out.reason=o.reason;if(o.sourceId!==undefined)out.sourceId=o.sourceId;if(o.candidate)out.candidate=descriptor(o.candidate);return out;};

export class SyncService {
 public constructor(private readonly scanner:CatalogScanner, private readonly deps:Deps={}, private readonly marker?:MarkerPort){}
 private normalized(input:SyncInput){const roots=normalizeRootDescriptors(input.roots);const selectors=[...new Set((input.selectors??[]).map((s)=>s.replaceAll('\\','/').replace(/^\.\//u,'')))].sort();return {roots,selectors};}
 private scan(input:{roots:SyncPreview['roots'];selectors:string[]}):CatalogCandidate[]{const result=this.scanner.scan(input);if(result instanceof Promise)throw new HubError('INTERNAL','async scanner cannot apply inside transaction',500);return result;}
 private manifest(candidates:CatalogCandidate[]){return [...candidates].map((c)=>descriptor(c)).sort((a,b)=>`${a.rootId}:${a.relativePath}:${a.kind}`.localeCompare(`${b.rootId}:${b.relativePath}:${b.kind}`));}
 private fingerprints(input:SyncInput,roots:SyncPreview['roots'],selectors:string[],candidates:CatalogCandidate[]){const manifest=this.manifest(candidates);const rootIds=roots.map((r)=>r.id);return {manifest,inputFingerprint:canonicalDigest({roots:rootIds,selectors,manifest}),rootsFingerprint:rootBindingsFingerprint(roots),profileFingerprint:this.deps.profileFingerprint?.(input.profile)??canonicalDigest(input.profile),targetFingerprint:this.deps.targetFingerprint?.(input)??canonicalDigest(input.target?.bytes??Buffer.alloc(0))};}
 public async preview(input:SyncInput, meta:MutationMeta={reason:'catalog.preview',requestId:`req_${randomUUID()}`}):Promise<SyncPreview>{
  const {roots,selectors}=this.normalized(input);
  const scanned=this.scanner.scan({roots,selectors});
  const candidates=scanned instanceof Promise?await scanned:scanned;
  return new SyncService(candidatesFrom(candidates),this.deps,this.marker).previewSync(input,meta);
 }
 public previewSync(input:SyncInput, meta:MutationMeta={reason:'catalog.preview',requestId:`req_${randomUUID()}`}):SyncPreview{
  if(!input.scope?.ownerUserId||!input.scope.agentId||!input.profile||!input.roots?.length) throw new HubError('VALIDATION','scope, profile and roots required',400);
  const {roots,selectors}=this.normalized(input);const scanned=this.scanner.scan({roots,selectors});
  if(scanned instanceof Promise) throw new HubError('INTERNAL','async scanner requires an asynchronous coordinator',500);
  const candidates=scanned;const seen=new Set<string>();const diagnostics:string[]=[];const operations:CatalogOperation[]=[];
  for(const candidate of [...candidates].sort((a,b)=>`${a.rootId??'default'}:${a.relativePath}`.localeCompare(`${b.rootId??'default'}:${b.relativePath}`))){const metadata=sanitizeMetadata(candidate.metadata??{});const key=logicalKey({kind:candidate.kind,root:candidate.rootId??'default',relativePath:candidate.relativePath,declaredName:typeof metadata.name==='string'?metadata.name:undefined});if(seen.has(key)){diagnostics.push(`duplicate:${key}`);operations.push({action:'conflict',logicalKey:key,reason:'duplicate logical key'});continue;}seen.add(key);let old:ReturnType<CatalogRepository['getByLogicalKey']>|undefined;try{old=this.deps.catalog?.getByLogicalKey(key,input.scope);}catch(error){if(!(error instanceof HubError)||error.code!=='NOT_FOUND')throw error;}operations.push({action:'upsert',logicalKey:key,expectedVersion:old?.currentVersion,candidate:{...candidate,metadata,summary:boundedSummary(candidate.summary),contentDigest:digestBytes(candidate.bytes)}});}
  if(this.deps.catalog){for(const old of this.deps.catalog.list(input.scope)){if(old.lifecycle==='active'&&!seen.has(old.logicalKey)&&this.inRoots(old.logicalKey,roots,selectors,old.metadata))operations.push({action:'stale',logicalKey:old.logicalKey,expectedVersion:old.currentVersion,reason:'not discovered'});}}
  const fp=this.fingerprints(input,roots,selectors,candidates);const catalogFingerprint=this.deps.catalog?canonicalDigest(this.deps.catalog.list(input.scope)):canonicalDigest([]);
  const digest=catalogSyncDigest({profile:input.profile,scope:input.scope,roots:roots.map((root)=>root.id),selectors,inputFingerprint:fp.inputFingerprint,rootsFingerprint:fp.rootsFingerprint,catalogFingerprint,profileFingerprint:fp.profileFingerprint,targetFingerprint:fp.targetFingerprint,operations:operations.map(opDescriptor),diagnostics});
  const preview:SyncPreview={id:`catprev_${randomUUID()}`,scope:input.scope,profile:input.profile,roots,selectors,inputFingerprint:fp.inputFingerprint,rootsFingerprint:fp.rootsFingerprint,catalogFingerprint,profileFingerprint:fp.profileFingerprint,targetFingerprint:fp.targetFingerprint,operations,diagnostics,complete:diagnostics.length===0,digest,expiresAt:input.expiresAt??Date.now()+300000};
  if(this.deps.sync)this.deps.sync.savePreview({...preview,operations:preview.operations.map((o)=>({...o,candidate:safeMeta(o.candidate)}))},meta);return preview;
 }
 public review(preview:SyncPreview,meta:MutationMeta):void {if(!preview.complete)throw new HubError('CONFLICT','incomplete preview',409);if(Date.now()>=preview.expiresAt)throw new HubError('CONFLICT','preview expired',409);this.deps.sync?.review(preview.id,preview.digest,preview.scope,meta);}
 public apply(request:{previewId:string;scope:SyncPreview['scope'];reviewedDigest?:string;observed?:SyncPreview;meta:MutationMeta}):void {
  if(!this.deps.sync||!this.deps.catalog)throw new HubError('INTERNAL','persistence is required',500);const p=this.deps.sync.getPreview(request.previewId,request.scope);const reviewed=request.reviewedDigest??request.observed?.digest;
  if(p.appliedAt){if(reviewed!==p.digest)throw new HubError('CONFLICT','replay digest mismatch',409);return;}if(!p.complete)throw new HubError('CONFLICT','incomplete preview',409);if(Date.now()>=p.expiresAt)throw new HubError('CONFLICT','preview expired',409);if(p.reviewedDigest!==p.digest)throw new HubError('CONFLICT','preview is not reviewed',409);if(reviewed!==p.digest)throw new HubError('CONFLICT','reviewed digest mismatch',409);
  const candidates=this.scan({roots:p.roots,selectors:p.selectors});const fp=this.fingerprints({roots:p.roots,selectors:p.selectors,scope:p.scope,profile:p.profile},p.roots,p.selectors,candidates);if(fp.inputFingerprint!==p.inputFingerprint||fp.rootsFingerprint!==p.rootsFingerprint||fp.profileFingerprint!==p.profileFingerprint||fp.targetFingerprint!==p.targetFingerprint)throw new HubError('CONFLICT','source/input/profile/target drift',409);
  if(canonicalDigest(this.deps.catalog.list(p.scope))!==p.catalogFingerprint)throw new HubError('CONFLICT','catalog drift',409);
  const byKey=new Map<string,CatalogCandidate>();for(const c of candidates){const metadata=sanitizeMetadata(c.metadata??{});const key=logicalKey({kind:c.kind,root:c.rootId??'default',relativePath:c.relativePath,declaredName:typeof metadata.name==='string'?metadata.name:undefined});if(byKey.has(key))throw new HubError('CONFLICT','duplicate source drift',409);byKey.set(key,{...c,metadata,summary:boundedSummary(c.summary),contentDigest:digestBytes(c.bytes)});}
  const expectedKeys=new Set(p.operations.filter(o=>o.action==='upsert').map(o=>o.logicalKey));if(expectedKeys.size!==byKey.size||[...expectedKeys].some(k=>!byKey.has(k)))throw new HubError('CONFLICT','source set drift',409);
  const operations=p.operations.map((op)=>{if(op.action==='conflict')throw new HubError('CONFLICT','conflict operation',409);const candidate=op.action==='upsert'?byKey.get(op.logicalKey):undefined;if(op.action==='upsert'&&!candidate)throw new HubError('CONFLICT','source drift',409);if(op.action==='upsert'&&candidate!.contentDigest!==op.candidate?.contentDigest)throw new HubError('CONFLICT','source content drift',409);let old:ReturnType<CatalogRepository['getByLogicalKey']>|undefined;try{old=this.deps.catalog!.getByLogicalKey(op.logicalKey,p.scope);}catch(e){if(!(e instanceof HubError)||e.code!=='NOT_FOUND')throw e;}if((old?.currentVersion??undefined)!==op.expectedVersion)throw new HubError('CONFLICT','catalog version drift',409);return {...op,candidate};});
  const freshDigest=catalogSyncDigest({profile:p.profile,scope:p.scope,roots:p.roots.map((root)=>root.id),selectors:p.selectors,inputFingerprint:fp.inputFingerprint,rootsFingerprint:p.rootsFingerprint,catalogFingerprint:p.catalogFingerprint,profileFingerprint:p.profileFingerprint,targetFingerprint:p.targetFingerprint,operations:operations.map(opDescriptor),diagnostics:p.diagnostics});
  if(freshDigest!==p.digest) throw new HubError('CONFLICT','persisted preview digest mismatch',409);
  const prior=this.marker?.snapshot();let touched=false;try{this.deps.catalog.applyPreview({...p,operations},request.meta);if(this.marker){touched=true;this.marker.write(Buffer.from(p.digest));this.deps.afterMarker?.();}this.deps.sync.markApplied(p.id,p.digest,p.scope,request.meta);}catch(error){if(touched&&prior)this.marker!.restore(prior);throw error;}
 }
 private inRoots(key:string,roots:SyncPreview['roots'],selectors:string[],metadata:Record<string,unknown>={}):boolean{const active=new Set(roots.map(r=>r.id));const root=typeof metadata.rootId==='string'?metadata.rootId:key.split(':')[1];const rel=typeof metadata.relativePath==='string'?metadata.relativePath:'';return active.has(root)&&(selectors.length===0||selectors.some((s)=>rel===s||rel.startsWith(`${s}/`)));}
}
export {canonicalDigest,logicalKey,sanitizeMetadata};
