import { describe, expect, it } from 'vitest';
import { mkdirSync, mkdtempSync, realpathSync, symlinkSync, unlinkSync, writeFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createActorContext, HubError, ProfileService, SyncService, candidatesFrom, logicalKey, type StorageTransaction } from '@portable-agent-asset-hub/core';
import { SqliteStore } from '@portable-agent-asset-hub/storage-sqlite';
import { CatalogSyncCoordinator, FileSyncMarker, RootScanner } from '@portable-agent-asset-hub/storage-files';
const actor=createActorContext({userId:'usr_s5',agentId:'agt_s5',role:'user',capabilities:[]});
const meta={reason:'test',requestId:'req_s5'};
function candidate(){return candidatesFrom([{kind:'document',relativePath:'a.md',locator:'a.md',bytes:Buffer.from('hello'),metadata:{name:'A',body:'must-not-persist'}}]);}
describe('S5 real catalog vertical slices',()=>{
 it('preview_digest_deterministic',async()=>{const a=await new SyncService(candidate()).preview({roots:['/r'],scope:actor.scope,profile:'p'});const b=await new SyncService(candidate()).preview({roots:['/r'],scope:actor.scope,profile:'p'});expect(b.digest).toBe(a.digest);});
 it('logical_key_stable',()=>{expect(logicalKey({kind:'document',root:'docs',relativePath:'same.md'})).toBe('document:docs:same.md');expect(logicalKey({kind:'document',root:'docs',relativePath:'same.md'})).not.toBe(logicalKey({kind:'document',root:'other',relativePath:'same.md'}));});
 it('apply_requires_reviewed_digest',async()=>{const db=new SqliteStore(join(mkdtempSync(join(tmpdir(),'s5-')),'a.sqlite'));const p=await new SyncService(candidate()).preview({roots:['/r'],scope:actor.scope,profile:'p'});db.transaction(actor,tx=>tx.catalogSync.savePreview(p,meta));expect(()=>db.transaction(actor,tx=>new SyncService(candidate(),{catalog:tx.catalog,sync:tx.catalogSync}).apply({previewId:p.id,scope:actor.scope,observed:p,meta}))).toThrow(/reviewed/);db.close();});
 it('apply_requires_exact_reviewed_digest',async()=>{const db=new SqliteStore(join(mkdtempSync(join(tmpdir(),'s5-')),'a.sqlite'));const p=await new SyncService(candidate()).preview({roots:['/r'],scope:actor.scope,profile:'p'});db.transaction(actor,tx=>tx.catalogSync.savePreview(p,meta));db.transaction(actor,tx=>tx.catalogSync.review(p.id,p.digest,actor.scope,meta));p.digest='0'.repeat(64);expect(()=>db.transaction(actor,tx=>new SyncService(candidate(),{catalog:tx.catalog,sync:tx.catalogSync}).apply({previewId:p.id,scope:actor.scope,observed:p,meta}))).toThrow(HubError);db.close();});
 it('apply_rejects_expired_preview',async()=>{const db=new SqliteStore(join(mkdtempSync(join(tmpdir(),'s5-')),'a.sqlite'));const p=await new SyncService(candidate()).preview({roots:['/r'],scope:actor.scope,profile:'p',expiresAt:Date.now()-1});db.transaction(actor,tx=>tx.catalogSync.savePreview(p,meta));expect(()=>db.transaction(actor,tx=>tx.catalogSync.review(p.id,p.digest,actor.scope,meta))).toThrow();db.close();});
 it('replayed_apply_is_noop',async()=>{const db=new SqliteStore(join(mkdtempSync(join(tmpdir(),'s5-')),'a.sqlite'));const p=await new SyncService(candidate()).preview({roots:['/r'],scope:actor.scope,profile:'p'});db.transaction(actor,tx=>tx.catalogSync.savePreview(p,meta));db.transaction(actor,tx=>tx.catalogSync.review(p.id,p.digest,actor.scope,meta));db.transaction(actor,tx=>new SyncService(candidate(),{catalog:tx.catalog,sync:tx.catalogSync}).apply({previewId:p.id,scope:actor.scope,observed:p,meta}));expect(()=>db.transaction(actor,tx=>new SyncService(candidate(),{catalog:tx.catalog,sync:tx.catalogSync}).apply({previewId:p.id,scope:actor.scope,observed:p,meta}))).not.toThrow();db.close();});
 it('relations_require_same_scope',()=>{const dir=mkdtempSync(join(tmpdir(),'s5-rel-'));const db=new SqliteStore(join(dir,'a.sqlite'));try{const entries=db.transaction(actor,tx=>{const base={scope:actor.scope,kind:'document' as const,summary:undefined,lifecycle:'active' as const,currentVersion:1,metadata:{}};const a=tx.catalog.upsert({...base,id:'cat_rel_a',logicalKey:'document:a.md',name:'a'},undefined,meta);const b=tx.catalog.upsert({...base,id:'cat_rel_b',logicalKey:'document:b.md',name:'b'},undefined,meta);tx.catalog.addSource({id:'src_rel',scope:actor.scope,kind:'document',locator:'a.md',fingerprint:'a'.repeat(64),createdAt:new Date().toISOString()},meta);return [a,b] as const;});const relation={scope:actor.scope,fromEntryId:entries[0].id,relation:'references',toEntryId:entries[1].id,sourceId:'src_rel'};db.transaction(actor,tx=>tx.catalog.relate(relation,meta));const first=db.transaction(actor,tx=>({stats:tx.catalog.stats(actor.scope),audit:tx.audit.list(actor.scope).length}));db.transaction(actor,tx=>tx.catalog.relate(relation,meta));const second=db.transaction(actor,tx=>({stats:tx.catalog.stats(actor.scope),audit:tx.audit.list(actor.scope).length}));expect(first.stats.relations).toBe(1);expect(second).toEqual(first);const other=createActorContext({userId:'usr_other',agentId:'agt_other',role:'user',capabilities:[]});expect(()=>db.transaction(other,tx=>tx.catalog.relate(relation,meta))).toThrow(HubError);}finally{db.close();rmSync(dir,{recursive:true,force:true});}});
 it('symlink_root_and_escape_rejected',()=>{const d=mkdtempSync(join(tmpdir(),'s5-'));const outside=mkdtempSync(join(tmpdir(),'out-'));writeFileSync(join(outside,'x.md'),'x');symlinkSync(outside,join(d,'link'));expect(()=>new RootScanner().scan({roots:[join(d,'link')]})).toThrow();expect(()=>new RootScanner().scan({roots:[d]})).toThrow();});
 it('partial_selector_does_not_stale_excluded_entries',()=>{const dir=mkdtempSync(join(tmpdir(),'s5-selector-'));const sourcePath=join(dir,'source');mkdirSync(join(sourcePath,'included'),{recursive:true});mkdirSync(join(sourcePath,'excluded'),{recursive:true});const source=realpathSync(sourcePath);writeFileSync(join(source,'included','a.md'),'a');writeFileSync(join(source,'excluded','b.md'),'b');const db=new SqliteStore(join(dir,'a.sqlite'));try{new ProfileService(db,actor).create({id:'prf_selector',scope:actor.scope,version:1,blocks:[{blockId:'user',ordinal:1,kind:'USER',body:'selector'}]},meta);const coordinator=new CatalogSyncCoordinator({storage:db,actor,scanner:new RootScanner(),marker:new FileSyncMarker(dir,'selector.marker')});const first=coordinator.preview({profileId:'prf_selector',roots:[{id:'source',path:source}]},meta);coordinator.review(first.id,first.digest,meta);coordinator.apply(first.id,first.digest,meta);unlinkSync(join(source,'included','a.md'));const second=coordinator.preview({profileId:'prf_selector',roots:[{id:'source',path:source}],selectors:['included']},meta);coordinator.review(second.id,second.digest,meta);coordinator.apply(second.id,second.digest,meta);const rows=db.transaction(actor,tx=>tx.catalog.list(actor.scope));expect(rows.find(row=>row.logicalKey.includes('included'))?.lifecycle).toBe('stale');expect(rows.find(row=>row.logicalKey.includes('excluded'))?.lifecycle).toBe('active');}finally{db.close();rmSync(dir,{recursive:true,force:true});}});
 it('metadata_sanitization_is_bounded',async()=>{const p=await new SyncService(candidatesFrom([{kind:'document',relativePath:'x',locator:'x',bytes:Buffer.from('secret'),metadata:{body:'secret',token:'abc',long:'x'.repeat(1000)}}])).preview({roots:['/r'],scope:actor.scope,profile:'p'});expect(JSON.stringify(p)).not.toContain('secret');expect(JSON.stringify(p)).not.toContain('abc');});
 it('transaction_repositories_expire',()=>{const db=new SqliteStore(join(mkdtempSync(join(tmpdir(),'s5-')),'a.sqlite'));let tx:StorageTransaction|undefined;db.transaction(actor,t=>{tx=t});expect(()=>tx!.catalog.list(actor.scope)).toThrow();db.close();});
 it('failure_rolls_back_entries_sources_audit_and_marker',async()=>{const dir=mkdtempSync(join(tmpdir(),'s5-'));const db=new SqliteStore(join(dir,'a.sqlite'));const marker={bytes:Buffer.from('prior'),snapshot:()=>({existed:true,bytes:Buffer.from(marker.bytes)}),write:(bytes:Buffer)=>{marker.bytes=Buffer.from(bytes)},restore:(prior:{existed:boolean;bytes?:Buffer})=>{marker.bytes=Buffer.from(prior.bytes??Buffer.alloc(0))}};try{const p=await new SyncService(candidate()).preview({roots:['/r'],scope:actor.scope,profile:'p'});db.transaction(actor,tx=>tx.catalogSync.savePreview(p,meta));db.transaction(actor,tx=>tx.catalogSync.review(p.id,p.digest,actor.scope,meta));const before=db.transaction(actor,tx=>({entries:tx.catalog.list(actor.scope).length,audit:tx.audit.list(actor.scope).length}));expect(()=>db.transaction(actor,tx=>new SyncService(candidate(),{catalog:tx.catalog,sync:new Proxy(tx.catalogSync,{get:(target,property,receiver)=>property==='markApplied'?()=>{throw new Error('audit hook failure')}:Reflect.get(target,property,receiver)})},marker).apply({previewId:p.id,reviewedDigest:p.digest,scope:actor.scope,meta}))).toThrow('audit hook failure');const after=db.transaction(actor,tx=>({entries:tx.catalog.list(actor.scope).length,audit:tx.audit.list(actor.scope).length}));expect(after).toEqual(before);expect(marker.bytes).toEqual(Buffer.from('prior'));}finally{db.close();rmSync(dir,{recursive:true,force:true});}});
});
