{
  "RequestId": {"name": "X-Request-Id", "in": "header", "schema": {"type": "string"}, "required": false},
  "IfMatch": {"name": "If-Match", "in": "header", "required": true, "schema": {"type": "string"}}
}
