import type { DatabaseSync } from 'node:sqlite';
import { createHash } from 'node:crypto';
import { canonicalDigest, HubError, safeRelativeLocator, type ActorContext, type CatalogEntry, type CatalogRelation, type CatalogSource, type CatalogRepository, type CatalogStats, type MutationMeta, type SyncPreview } from '@portable-agent-asset-hub/core';
import { AuditRepository } from './repositories/audit.js';
type Row=Record<string,unknown>; const now=()=>new Date().toISOString();
export class SqliteCatalogRepository implements CatalogRepository {
 constructor(private readonly db:DatabaseSync, private readonly actor?:ActorContext, private readonly audit?:AuditRepository, private readonly assertActive=()=>{}){}
 private guard(){this.assertActive(); if(!this.actor||!this.audit)throw new HubError('FORBIDDEN','actor-bound catalog repository required',403);}
 private event(action:string,target:string,meta:MutationMeta){this.audit!.append({action,actor:{userId:this.actor!.userId,agentId:this.actor!.agentId,harnessId:this.actor!.harnessId},scope:this.actor!.scope,target,requestDigest:meta.requestId,metadata:{reason:meta.reason}});}
 list(scope:{ownerUserId:string;agentId:string}):CatalogEntry[]{this.guardScope(scope);return (this.db.prepare('SELECT * FROM catalog_entries WHERE owner_user_id=? AND scope_agent_id=? ORDER BY logical_key').all(scope.ownerUserId,scope.agentId) as Row[]).map(this.map);}
 listSources(scope:{ownerUserId:string;agentId:string}):CatalogSource[]{this.guardScope(scope);return (this.db.prepare('SELECT * FROM catalog_sources WHERE owner_user_id=? AND scope_agent_id=? ORDER BY id').all(scope.ownerUserId,scope.agentId) as Row[]).map((row)=>({id:String(row.id),scope:{ownerUserId:String(row.owner_user_id) as `usr_${string}`,agentId:String(row.scope_agent_id) as `agt_${string}`},kind:String(row.kind),locator:String(row.locator),fingerprint:String(row.fingerprint),createdAt:String(row.created_at)}));}
 stats(scope:{ownerUserId:string;agentId:string}):CatalogStats{this.guardScope(scope);const count=(table:string)=>Number((this.db.prepare(`SELECT COUNT(*) AS count FROM ${table} WHERE owner_user_id=? AND scope_agent_id=?`).get(scope.ownerUserId,scope.agentId) as Row).count);return {entries:count('catalog_entries'),versions:count('catalog_entry_versions'),sources:count('catalog_sources'),links:count('catalog_entry_sources'),relations:count('catalog_relations')};}
 getByLogicalKey(key:string,scope:{ownerUserId:string;agentId:string}):CatalogEntry{this.guardScope(scope);const r=this.db.prepare('SELECT * FROM catalog_entries WHERE logical_key=? AND owner_user_id=? AND scope_agent_id=?').get(key,scope.ownerUserId,scope.agentId) as Row|undefined;if(!r)throw new HubError('NOT_FOUND','catalog entry not found',404);return this.map(r);}
 search(scope:{ownerUserId:string;agentId:string},query:string,limit=20,kind?:CatalogEntry['kind']):CatalogEntry[]{this.guardScope(scope);const q=query.trim();if(!q)throw new HubError('VALIDATION','q must be a non-empty string',400);if(!Number.isInteger(limit)||limit<1||limit>100)throw new HubError('VALIDATION','limit must be an integer between 1 and 100',400);const expression=q.split(/\s+/u).map((token)=>`"${token.replaceAll('"','""')}"`).join(' AND ');const sql="SELECT e.* FROM catalog_fts f JOIN catalog_entries e ON e.id=f.entry_id AND e.owner_user_id=f.owner_user_id AND e.scope_agent_id=f.scope_agent_id WHERE f.owner_user_id=? AND f.scope_agent_id=? AND catalog_fts MATCH ? AND e.lifecycle='active'"+(kind?' AND f.kind=?':'')+' ORDER BY bm25(catalog_fts), e.logical_key LIMIT ?';const args:(string|number)[]=[scope.ownerUserId,scope.agentId,expression];if(kind)args.push(kind);args.push(limit);return (this.db.prepare(sql).all(...args) as Row[]).map(this.map);}
 private guardScope(scope:{ownerUserId:string;agentId:string}):void { this.assertActive(); if(!this.actor||scope.ownerUserId!==this.actor.scope.ownerUserId||scope.agentId!==this.actor.scope.agentId)throw new HubError('NOT_FOUND','catalog entry not found',404); }
 upsert(entry:Omit<CatalogEntry,'createdAt'|'updatedAt'>,expectedVersion:number|undefined,meta:MutationMeta):CatalogEntry{this.guard(); if(entry.scope.ownerUserId!==this.actor!.scope.ownerUserId||entry.scope.agentId!==this.actor!.scope.agentId)throw new HubError('NOT_FOUND','catalog entry not found',404);const t=now();let old:CatalogEntry|undefined;try{old=this.getByLogicalKey(entry.logicalKey,entry.scope);}catch(e){if(!(e instanceof HubError)||e.code!=='NOT_FOUND')throw e;}
  if(old){if(expectedVersion!==old.currentVersion)throw new HubError('CONFLICT','catalog CAS conflict',409);const v=old.currentVersion+1;const result=this.db.prepare('UPDATE catalog_entries SET name=?,summary=?,lifecycle=?,current_version=?,metadata_json=?,updated_at=? WHERE id=? AND owner_user_id=? AND scope_agent_id=? AND current_version=?').run(entry.name,entry.summary??null,entry.lifecycle,v,JSON.stringify(entry.metadata),t,old.id,entry.scope.ownerUserId,entry.scope.agentId,old.currentVersion);if(Number(result.changes)!==1)throw new HubError('CONFLICT','catalog CAS conflict',409);this.db.prepare('INSERT INTO catalog_entry_versions(entry_id,owner_user_id,scope_agent_id,version,snapshot_json,created_at) VALUES(?,?,?,?,?,?)').run(old.id,entry.scope.ownerUserId,entry.scope.agentId,v,JSON.stringify({...entry,currentVersion:v,createdAt:old.createdAt,updatedAt:t}),t);const out={...entry,id:old.id,currentVersion:v,createdAt:old.createdAt,updatedAt:t};this.event('catalog.entry.updated',out.id,meta);return out;}
  if(expectedVersion!==undefined&&expectedVersion!==0)throw new HubError('CONFLICT','catalog create CAS conflict',409);this.db.prepare('INSERT INTO catalog_entries VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').run(entry.id,entry.scope.ownerUserId,entry.scope.agentId,entry.logicalKey,entry.kind,entry.name,entry.summary??null,entry.lifecycle,1,JSON.stringify(entry.metadata),t,t);this.db.prepare('INSERT INTO catalog_entry_versions(entry_id,owner_user_id,scope_agent_id,version,snapshot_json,created_at) VALUES(?,?,?,?,?,?)').run(entry.id,entry.scope.ownerUserId,entry.scope.agentId,1,JSON.stringify({...entry,currentVersion:1,createdAt:t,updatedAt:t}),t);const out={...entry,currentVersion:1,createdAt:t,updatedAt:t};this.event('catalog.entry.created',out.id,meta);return out;}
 addSource(source:CatalogSource,meta:MutationMeta):CatalogSource{this.guard();if(source.scope.ownerUserId!==this.actor!.scope.ownerUserId||source.scope.agentId!==this.actor!.scope.agentId)throw new HubError('NOT_FOUND','source not found',404);let locator:string;try{locator=safeRelativeLocator(source.locator);}catch{throw new HubError('VALIDATION','unsafe source locator',400);}const safe={...source,locator,id:source.id||`src_${canonicalDigest({kind:source.kind,locator,scope:source.scope}).slice(0,24)}`};const r=this.db.prepare('INSERT OR IGNORE INTO catalog_sources VALUES(?,?,?,?,?,?,?)').run(safe.id,safe.scope.ownerUserId,safe.scope.agentId,safe.kind,safe.locator,safe.fingerprint,safe.createdAt);if(Number(r.changes)===1){this.event('catalog.source.added',safe.id,meta);return safe;}const row=this.db.prepare('SELECT id,fingerprint,created_at FROM catalog_sources WHERE owner_user_id=? AND scope_agent_id=? AND kind=? AND locator=?').get(safe.scope.ownerUserId,safe.scope.agentId,safe.kind,safe.locator) as Row|undefined;if(!row)throw new HubError('CONFLICT','catalog source id already used for a different locator',409);const persisted:CatalogSource={...safe,id:String(row.id),fingerprint:String(row.fingerprint),createdAt:String(row.created_at)};if(persisted.fingerprint===safe.fingerprint)return persisted;this.db.prepare('UPDATE catalog_sources SET fingerprint=? WHERE id=? AND owner_user_id=? AND scope_agent_id=?').run(safe.fingerprint,persisted.id,safe.scope.ownerUserId,safe.scope.agentId);this.event('catalog.source.refingerprinted',persisted.id,meta);return {...persisted,fingerprint:safe.fingerprint};}
 link(entryId:string,sourceId:string,scope:{ownerUserId:string;agentId:string},meta:MutationMeta):void{this.guard();this.guardScope(scope);const e=this.db.prepare('SELECT 1 FROM catalog_entries WHERE id=? AND owner_user_id=? AND scope_agent_id=?').get(entryId,scope.ownerUserId,scope.agentId);const s=this.db.prepare('SELECT 1 FROM catalog_sources WHERE id=? AND owner_user_id=? AND scope_agent_id=?').get(sourceId,scope.ownerUserId,scope.agentId);if(!e||!s)throw new HubError('NOT_FOUND','source or entry not found',404);const r=this.db.prepare('INSERT OR IGNORE INTO catalog_entry_sources VALUES(?,?,?,?)').run(entryId,sourceId,scope.ownerUserId,scope.agentId);if(Number(r.changes)===1)this.event('catalog.source.linked',entryId,meta);}
 relate(r:CatalogRelation,meta:MutationMeta):void{this.guard();this.guardScope(r.scope);const from=this.db.prepare('SELECT 1 FROM catalog_entries WHERE id=? AND owner_user_id=? AND scope_agent_id=?').get(r.fromEntryId,r.scope.ownerUserId,r.scope.agentId);const to=this.db.prepare('SELECT 1 FROM catalog_entries WHERE id=? AND owner_user_id=? AND scope_agent_id=?').get(r.toEntryId,r.scope.ownerUserId,r.scope.agentId);if(!from||!to||(r.sourceId&&!this.db.prepare('SELECT 1 FROM catalog_sources WHERE id=? AND owner_user_id=? AND scope_agent_id=?').get(r.sourceId,r.scope.ownerUserId,r.scope.agentId)))throw new HubError('NOT_FOUND','relation endpoint not found',404);const result=this.db.prepare('INSERT OR IGNORE INTO catalog_relations VALUES(?,?,?,?,?,?)').run(r.scope.ownerUserId,r.scope.agentId,r.fromEntryId,r.relation,r.toEntryId,r.sourceId??null);if(Number(result.changes)===1)this.event('catalog.relation.added',`${r.fromEntryId}:${r.relation}:${r.toEntryId}`,meta);}
 applyPreview(preview:SyncPreview,meta:MutationMeta):void{this.guard();for(const op of preview.operations){if(op.action==='stale'){const old=this.getByLogicalKey(op.logicalKey,preview.scope);this.upsert({...old,lifecycle:'stale'},op.expectedVersion,meta);continue;}if(op.action==='upsert'&&op.candidate){let old:CatalogEntry|undefined;try{old=this.getByLogicalKey(op.logicalKey,preview.scope);}catch(e){if(!(e instanceof HubError)||e.code!=='NOT_FOUND')throw e;}const c=op.candidate;const contentDigest=c.contentDigest??createHash('sha256').update(c.bytes).digest('hex');const locator=safeRelativeLocator(c.locator);const rootId=c.rootId??'default';const entry:Omit<CatalogEntry,'createdAt'|'updatedAt'>={id:old?.id??`cat_${canonicalDigest(op.logicalKey).slice(0,24)}`,scope:preview.scope,logicalKey:op.logicalKey,kind:c.kind,name:String(c.metadata?.name??c.relativePath),summary:c.summary,lifecycle:'active',currentVersion:old?.currentVersion??1,metadata:{...c.metadata,sha256:contentDigest,rootId,relativePath:c.relativePath}};const saved=this.upsert(entry,op.expectedVersion,meta);const source:CatalogSource={id:`src_${canonicalDigest({kind:c.sourceKind??c.kind,rootId,locator}).slice(0,24)}`,scope:preview.scope,kind:c.sourceKind??c.kind,locator,fingerprint:contentDigest,createdAt:now()};const safeSource=this.addSource(source,meta);this.link(saved.id,safeSource.id,preview.scope,meta);}}}
 private map=(r:Row):CatalogEntry=>({id:String(r.id),scope:{ownerUserId:String(r.owner_user_id) as `usr_${string}`,agentId:String(r.scope_agent_id) as `agt_${string}`},logicalKey:String(r.logical_key),kind:r.kind as CatalogEntry['kind'],name:String(r.name),summary:typeof r.summary==='string'?r.summary:undefined,lifecycle:r.lifecycle as CatalogEntry['lifecycle'],currentVersion:Number(r.current_version),metadata:JSON.parse(String(r.metadata_json)) as Record<string,unknown>,createdAt:String(r.created_at),updatedAt:String(r.updated_at)});
 fingerprint(scope:{ownerUserId:string;agentId:string}):string{return canonicalDigest(this.list(scope));}
}
