import type { DatabaseSync } from 'node:sqlite';
import { createHash } from 'node:crypto';
import { HubError, type ActorContext, type CatalogSyncRepository, type MutationMeta, type SyncPreview } from '@portable-agent-asset-hub/core';
import { AuditRepository } from './repositories/audit.js';
type Scope={ownerUserId:string;agentId:string};type Row=Record<string,unknown>;
export class SqliteCatalogSyncRepository implements CatalogSyncRepository{
 constructor(private readonly db:DatabaseSync,private readonly actor?:ActorContext,private readonly audit?:AuditRepository,private readonly assertActive=()=>{}){}
 private guard(){this.assertActive();if(!this.actor||!this.audit)throw new HubError('FORBIDDEN','actor-bound catalog repository required',403);}
 private event(action:string,target:string,meta:MutationMeta){this.audit!.append({action,actor:{userId:this.actor!.userId,agentId:this.actor!.agentId,harnessId:this.actor!.harnessId},scope:this.actor!.scope,target,requestDigest:meta.requestId,metadata:{reason:meta.reason}});}
 savePreview(p:SyncPreview,meta:MutationMeta):SyncPreview{this.guard();if(p.scope.ownerUserId!==this.actor!.scope.ownerUserId||p.scope.agentId!==this.actor!.scope.agentId)throw new HubError('NOT_FOUND','preview not found',404);const safe={...p,operations:p.operations.map((o)=>({...o,candidate:o.candidate?{...o.candidate,bytes:Buffer.alloc(0),contentDigest:o.candidate.contentDigest??createHash('sha256').update(o.candidate.bytes).digest('hex')}:undefined}))};this.db.prepare('INSERT INTO catalog_sync_previews VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(safe.id,safe.scope.ownerUserId,safe.scope.agentId,safe.profile,JSON.stringify(safe.roots),JSON.stringify(safe.selectors),safe.inputFingerprint,safe.rootsFingerprint,safe.catalogFingerprint,safe.profileFingerprint,safe.targetFingerprint,safe.digest,JSON.stringify(safe.operations),JSON.stringify(safe.diagnostics),safe.complete?1:0,safe.expiresAt,safe.reviewedDigest??null,safe.appliedAt??null);this.event('catalog.preview.created',safe.id,meta);return safe;}
 getPreview(id:string,s:Scope):SyncPreview{this.guard();if(s.ownerUserId!==this.actor!.scope.ownerUserId||s.agentId!==this.actor!.scope.agentId)throw new HubError('NOT_FOUND','preview not found',404);const r=this.db.prepare('SELECT * FROM catalog_sync_previews WHERE id=? AND owner_user_id=? AND scope_agent_id=?').get(id,s.ownerUserId,s.agentId) as Row|undefined;if(!r)throw new HubError('NOT_FOUND','preview not found',404);return {id:String(r.id),scope:{ownerUserId:String(r.owner_user_id) as `usr_${string}`,agentId:String(r.scope_agent_id) as `agt_${string}`},profile:String(r.profile),roots:JSON.parse(String(r.roots_json)) as SyncPreview['roots'],selectors:JSON.parse(String(r.selectors_json)) as string[],inputFingerprint:String(r.input_fingerprint),rootsFingerprint:String(r.roots_fingerprint),catalogFingerprint:String(r.catalog_fingerprint),profileFingerprint:String(r.profile_fingerprint),targetFingerprint:String(r.target_fingerprint),digest:String(r.digest),operations:JSON.parse(String(r.operations_json)) as SyncPreview['operations'],diagnostics:JSON.parse(String(r.diagnostics_json)) as string[],complete:Boolean(r.complete),expiresAt:Number(r.expires_at),reviewedDigest:typeof r.reviewed_digest==='string'?r.reviewed_digest:undefined,appliedAt:r.applied_at!=null?String(r.applied_at):undefined};}
 review(id:string,digest:string,s:Scope,meta:MutationMeta):void{this.guard();const r=this.db.prepare('UPDATE catalog_sync_previews SET reviewed_digest=? WHERE id=? AND owner_user_id=? AND scope_agent_id=? AND digest=? AND applied_at IS NULL AND expires_at>?').run(digest,id,s.ownerUserId,s.agentId,digest,Date.now());if(Number(r.changes)!==1)throw new HubError('CONFLICT','preview review mismatch',409);this.event('catalog.preview.reviewed',id,meta);}
 markApplied(id:string,digest:string,s:Scope,meta:MutationMeta):void{this.guard();const r=this.db.prepare('UPDATE catalog_sync_previews SET applied_at=? WHERE id=? AND owner_user_id=? AND scope_agent_id=? AND digest=? AND reviewed_digest=? AND applied_at IS NULL').run(new Date().toISOString(),id,s.ownerUserId,s.agentId,digest,digest);if(Number(r.changes)!==1)throw new HubError('CONFLICT','preview apply marker conflict',409);this.event('catalog.preview.applied',id,meta);}
}
