import { afterEach, describe, expect, it } from 'vitest';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { boundedAuditQuery, createActorContext, classifyRetrievalRequest, retrievalKeywords, retrievalPolicy, type ActorContext, type SkillRelationInput } from '@portable-agent-asset-hub/core';
import { SqliteStore } from '@portable-agent-asset-hub/storage-sqlite';

const roots: string[] = [];
afterEach(() => { for (const root of roots.splice(0)) rmSync(root, { recursive: true, force: true }); });
function fixture() { const root=mkdtempSync(join(tmpdir(),'skill-graph-'));roots.push(root);const store=new SqliteStore(join(root,'hub.sqlite'));const actor=createActorContext({userId:'usr_local',agentId:'agt_local',role:'admin',capabilities:['read','write.skill','admin']});return {store,actor}; }
function write(store: SqliteStore, actor: ActorContext, id: string, text=id, relations?: SkillRelationInput[], expectedVersion?: number) {
  return store.transaction(actor,(tx)=>tx.skills.writeSkill({id,scope:actor.scope,logicalKey:`skill:default:${id}`,kind:'skill',name:id.replace(/^skl_/u,''),summary:text,lifecycle:'active',body:Buffer.from(`# ${text}\n${text}`),metadata:{tags:[text]},resources:[],...(relations!==undefined?{relations}:{}),...(expectedVersion!==undefined?{expectedVersion}:{})},{reason:'test',requestId:`req_${id}_${expectedVersion??0}`}));
}

describe('migration 0016 skill graph',()=>{
  it('migrates schema 16 to 18 without inventing relations and doctor is green',async()=>{const {store}=fixture();try{const {DatabaseSync}=await import('node:sqlite');const db=(store as unknown as {diagnostics():unknown});expect(db).toBeDefined();expect(store.doctor().ok).toBe(true);const root=roots[0]!;store.close();const probe=new DatabaseSync(join(root,'hub.sqlite'));expect((probe.prepare('SELECT MAX(version) AS v FROM schema_meta').get() as {v:number}).v).toBe(19);expect((probe.prepare('SELECT COUNT(*) AS n FROM skill_relations').get() as {n:number}).n).toBe(0);expect((probe.prepare('PRAGMA integrity_check').get() as {integrity_check:string}).integrity_check).toBe('ok');probe.close();}finally{try{store.close();}catch{/* already closed */}}});
  it('creates requires, resolves direct/transitive dependencies, and lists dependents deterministically',()=>{const {store,actor}=fixture();try{write(store,actor,'skl_c','container registry');write(store,actor,'skl_b','docker build',[{type:'requires',targetSkillId:'skl_c',targetVersion:1}]);write(store,actor,'skl_a','kubernetes deployment',[{type:'requires',targetSkillId:'skl_b',targetVersionConstraint:'>=1'}]);const graph=store.transaction(actor,tx=>tx.skills.resolveGraph('skl_a',1,actor.scope));expect(graph.resolved.map(n=>[n.skillId,n.version,n.depth])).toEqual([['skl_b',1,1],['skl_c',1,2]]);expect(store.transaction(actor,tx=>tx.skills.getDependents('skl_b',actor.scope)).map(r=>r.sourceSkillId)).toEqual(['skl_a']);}finally{store.close();}});
  it('rejects missing targets, duplicates, self relations, invalid constraints, and requires cycles',()=>{const {store,actor}=fixture();try{write(store,actor,'skl_a');write(store,actor,'skl_b');expect(()=>store.transaction(actor,tx=>tx.skills.replaceRelations('skl_a',1,[{type:'requires',targetSkillId:'skl_missing',targetVersion:1}],actor.scope,{reason:'x',requestId:'req_missing'}))).toThrow(expect.objectContaining({code:'NOT_FOUND'}));expect(()=>store.transaction(actor,tx=>tx.skills.replaceRelations('skl_a',1,[{type:'requires',targetSkillId:'skl_b',targetVersion:1},{type:'requires',targetSkillId:'skl_b',targetVersion:1}],actor.scope,{reason:'x',requestId:'req_dup'}))).toThrow(expect.objectContaining({code:'CONFLICT'}));expect(()=>store.transaction(actor,tx=>tx.skills.replaceRelations('skl_a',1,[{type:'requires',targetSkillId:'skl_a',targetVersion:1}],actor.scope,{reason:'x',requestId:'req_self'}))).toThrow();expect(()=>store.transaction(actor,tx=>tx.skills.replaceRelations('skl_a',1,[{type:'requires',targetSkillId:'skl_b',targetVersionConstraint:'semver-ish'}],actor.scope,{reason:'x',requestId:'req_bad'}))).toThrow(expect.objectContaining({code:'VALIDATION'}));store.transaction(actor,tx=>tx.skills.replaceRelations('skl_a',1,[{type:'requires',targetSkillId:'skl_b',targetVersion:1}],actor.scope,{reason:'x',requestId:'req_ab'}));expect(()=>store.transaction(actor,tx=>tx.skills.replaceRelations('skl_b',1,[{type:'requires',targetSkillId:'skl_a',targetVersion:2}],actor.scope,{reason:'x',requestId:'req_ba'}))).toThrow(expect.objectContaining({code:'CONFLICT'}));}finally{store.close();}});
  it('rejects supersedes cycles because the relation registry marks them acyclic',()=>{const {store,actor}=fixture();try{write(store,actor,'skl_a');write(store,actor,'skl_b');store.transaction(actor,tx=>tx.skills.replaceRelations('skl_a',1,[{type:'supersedes',targetSkillId:'skl_b',targetVersion:1}],actor.scope,{reason:'supersede b',requestId:'req_supersedes_ab'}));expect(()=>store.transaction(actor,tx=>tx.skills.replaceRelations('skl_b',1,[{type:'supersedes',targetSkillId:'skl_a',targetVersion:2}],actor.scope,{reason:'supersede a',requestId:'req_supersedes_ba'}))).toThrow(expect.objectContaining({code:'CONFLICT'}));}finally{store.close();}});
  it('allows related_to cycles and enforces graph depth/node limits',()=>{const {store,actor}=fixture();try{write(store,actor,'skl_c');write(store,actor,'skl_b','b',[{type:'requires',targetSkillId:'skl_c',targetVersion:1}]);write(store,actor,'skl_a','a',[{type:'requires',targetSkillId:'skl_b',targetVersion:1}]);expect(store.transaction(actor,tx=>tx.skills.resolveGraph('skl_a',1,actor.scope,{maxDepth:1})).resolved.map(n=>n.skillId)).toEqual(['skl_b']);expect(()=>store.transaction(actor,tx=>tx.skills.resolveGraph('skl_a',1,actor.scope,{maxResolvedSkills:1}))).toThrow(expect.objectContaining({status:413}));write(store,actor,'skl_x');write(store,actor,'skl_y');store.transaction(actor,tx=>tx.skills.replaceRelations('skl_x',1,[{type:'related_to',targetSkillId:'skl_y'}],actor.scope,{reason:'x',requestId:'req_xr'}));store.transaction(actor,tx=>tx.skills.replaceRelations('skl_y',1,[{type:'related_to',targetSkillId:'skl_x'}],actor.scope,{reason:'x',requestId:'req_yr'}));expect(store.doctor().checks.skillDependencyGraphAcyclic).toBe(true);expect(store.transaction(actor,tx=>tx.skills.resolveGraph('skl_x',2,actor.scope)).resolved).toEqual([]);}finally{store.close();}});
  it.each(['requires','supersedes'] as const)('reports a directly injected %s cycle through doctor',async(relationType)=>{const {store,actor}=fixture();const root=roots[0]!;write(store,actor,'skl_a');write(store,actor,'skl_b');store.close();const {DatabaseSync}=await import('node:sqlite');const db=new DatabaseSync(join(root,'hub.sqlite'));const insert=db.prepare(`INSERT INTO skill_relations(source_skill_id,source_version,owner_user_id,scope_agent_id,relation_type,target_skill_id,target_version_constraint,resolved_target_version,metadata_json,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)`);const args=(source:string,target:string)=>[source,1,actor.scope.ownerUserId,actor.scope.agentId,relationType,target,'=1',1,'{}',new Date(0).toISOString()] as const;insert.run(...args('skl_a','skl_b'));insert.run(...args('skl_b','skl_a'));db.close();const reopened=new SqliteStore(join(root,'hub.sqlite'));try{const result=reopened.doctor();expect(result.ok).toBe(false);expect(result.checks.skillDependencyGraphAcyclic).toBe(false);}finally{reopened.close();}});
  it('fails closed when a required target is stale and doctor reports the graph unresolved',()=>{const {store,actor}=fixture();try{write(store,actor,'skl_b');write(store,actor,'skl_a','a',[{type:'requires',targetSkillId:'skl_b',targetVersion:1}]);store.transaction(actor,tx=>tx.skills.writeSkill({id:'skl_b',scope:actor.scope,logicalKey:'skill:skl_b',kind:'skill',name:'skl_b',lifecycle:'stale',body:Buffer.from('stale'),metadata:{},resources:[],expectedVersion:1},{reason:'archive',requestId:'req_archive'}));expect(()=>store.transaction(actor,tx=>tx.skills.resolveGraph('skl_a',1,actor.scope))).toThrow(expect.objectContaining({code:'NOT_FOUND'}));expect(store.doctor().checks.skillGraphResolvable).toBe(false);}finally{store.close();}});

  it('returns an explicit conflict when two dependency paths snapshot incompatible target versions',()=>{const {store,actor}=fixture();try{write(store,actor,'skl_b','b1');write(store,actor,'skl_b','b2',undefined,1);write(store,actor,'skl_c','c',[{type:'requires',targetSkillId:'skl_b',targetVersion:2}]);write(store,actor,'skl_a','a',[{type:'requires',targetSkillId:'skl_b',targetVersion:1},{type:'requires',targetSkillId:'skl_c',targetVersion:1}]);expect(()=>store.transaction(actor,tx=>tx.skills.resolveGraph('skl_a',1,actor.scope))).toThrow(expect.objectContaining({code:'CONFLICT'}));expect(store.doctor().checks.skillGraphResolvable).toBe(false);}finally{store.close();}});
  it('does not leak relations or dependency targets across actor scope',()=>{const {store,actor}=fixture();try{write(store,actor,'skl_b');write(store,actor,'skl_a','a',[{type:'requires',targetSkillId:'skl_b',targetVersion:1}]);const outsider=createActorContext({userId:'usr_other',agentId:'agt_other',role:'user',capabilities:['read']});expect(()=>store.transaction(outsider,tx=>tx.skills.getRelations('skl_a',1,outsider.scope))).toThrow(expect.objectContaining({code:'NOT_FOUND'}));expect(()=>store.transaction(outsider,tx=>tx.skills.resolveGraph('skl_a',1,outsider.scope))).toThrow(expect.objectContaining({code:'NOT_FOUND'}));expect(store.transaction(outsider,tx=>tx.skills.resolveRetrieval('Deploy kubernetes','default',outsider.scope)).skills).toEqual([]);}finally{store.close();}});
  it('applies secret scanning to relation metadata and rolls back the write',()=>{const {store,actor}=fixture();try{write(store,actor,'skl_b');write(store,actor,'skl_a');expect(()=>store.transaction(actor,tx=>tx.skills.replaceRelations('skl_a',1,[{type:'requires',targetSkillId:'skl_b',targetVersion:1,metadata:{credential:'AKIAABCDEFGHIJKLMNOP'}}],actor.scope,{reason:'secret',requestId:'req_secret'}))).toThrow(expect.objectContaining({code:'VALIDATION'}));expect(store.transaction(actor,tx=>tx.skills.getRelations('skl_a',1,actor.scope))).toEqual([]);}finally{store.close();}});

  it('canonicalizes relation metadata so key order does not create a version',()=>{const {store,actor}=fixture();try{write(store,actor,'skl_b');write(store,actor,'skl_a');const changed=store.transaction(actor,tx=>tx.skills.replaceRelations('skl_a',1,[{type:'requires',targetSkillId:'skl_b',targetVersion:1,metadata:{z:1,a:2}}],actor.scope,{reason:'metadata',requestId:'req_meta_1'}));const same=store.transaction(actor,tx=>tx.skills.replaceRelations('skl_a',changed.version,[{type:'requires',targetSkillId:'skl_b',targetVersion:1,metadata:{a:2,z:1}}],actor.scope,{reason:'metadata',requestId:'req_meta_2'}));expect(same.version).toBe(changed.version);}finally{store.close();}});

  it('snapshots target resolution and relation changes create a new source version without mutating history',()=>{const {store,actor}=fixture();try{write(store,actor,'skl_b','v1');write(store,actor,'skl_a','root',[{type:'requires',targetSkillId:'skl_b',targetVersionConstraint:'>=1'}]);write(store,actor,'skl_b','v2',undefined,1);expect(store.transaction(actor,tx=>tx.skills.resolveGraph('skl_a',1,actor.scope)).resolved[0]?.version).toBe(1);const a2=store.transaction(actor,tx=>tx.skills.replaceRelations('skl_a',1,[{type:'requires',targetSkillId:'skl_b',targetVersionConstraint:'>=1'}],actor.scope,{reason:'advance',requestId:'req_advance'}));expect(a2.version).toBe(2);expect(store.transaction(actor,tx=>tx.skills.resolveGraph('skl_a',2,actor.scope)).resolved[0]?.version).toBe(2);expect(store.transaction(actor,tx=>tx.skills.getRelations('skl_a',1,actor.scope))[0]?.resolvedTargetVersion).toBe(1);}finally{store.close();}});
});

describe('mandatory retrieval policy and resolver',()=>{
  it('falls back to bounded raw tokens so mandatory discovery still runs when every preferred term is filtered',()=>{expect(retrievalKeywords('how to')).toEqual(['how','to']);const {store,actor}=fixture();try{write(store,actor,'skl_how_guide','how guide procedure');const resolution=store.transaction(actor,tx=>tx.skills.resolveRetrieval('how to','default',actor.scope,{supportingThreshold:0.3}));expect(resolution.policy.skillRetrievalRequired).toBe(true);expect(resolution.candidatesConsidered).toBeGreaterThan(0);expect(resolution.skills.map(skill=>skill.skillId)).toContain('skl_how_guide');}finally{store.close();}});
  it('redacts common authorization, cookie, cloud, client-secret, and JWT forms before audit',()=>{const jwt='eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMjMifQ.signature';const raw=`Authorization: Basic dXNlcjpwYXNz cookie=session-value aws_access_key_id=AKIAEXAMPLE client_secret=client-value jwt=${jwt}`;const redacted=boundedAuditQuery(raw);for(const secret of ['dXNlcjpwYXNz','session-value','AKIAEXAMPLE','client-value',jwt]) expect(redacted).not.toContain(secret);expect(redacted).toContain('[REDACTED]');});
  it.each([
    ['Explain what a mutex is',false,false],['Deploy this API to Kubernetes',true,false],['Debug this failing service',true,false],['Migra esta aplicación',true,false],['recuerda mi preferencia',false,true],['Despliega mi proyecto como solemos hacerlo',true,true],
  ])('%s', (query,skills,memory)=>{const decision=retrievalPolicy(classifyRetrievalRequest(query));expect(decision.skillRetrievalRequired).toBe(skills);expect(decision.memoryRetrievalRequired).toBe(memory);});
  it('runs FTS discovery, expands the graph, ignores low-score matches, records match and no-match audits',async()=>{const {store,actor}=fixture();try{write(store,actor,'skl_docker_build','docker build container image');write(store,actor,'skl_kubernetes_deployment','kubernetes deployment api helm',[{type:'requires',targetSkillId:'skl_docker_build',targetVersion:1}]);const matched=store.transaction(actor,tx=>tx.skills.resolveRetrieval('Despliega esta API en Kubernetes','default',actor.scope,{supportingThreshold:0.3}));expect(matched.policy.skillRetrievalRequired).toBe(true);expect(matched.skills.map(s=>s.skillId)).toContain('skl_kubernetes_deployment');expect(matched.skills).toContainEqual(expect.objectContaining({skillId:'skl_docker_build',reason:'dependency'}));expect(matched.materialization.selectedBytes).toBeGreaterThan(0);expect(()=>store.transaction(actor,tx=>tx.skills.resolveRetrieval('Despliega esta API en Kubernetes','default',actor.scope,{supportingThreshold:0.3,maxBodyBytes:1}))).toThrow(expect.objectContaining({status:413}));store.transaction(actor,tx=>tx.memories.create({kind:'preference',scope:actor.scope,scopeKey:'deployment',content:{text:'kubernetes deployment preference helm'},reason:'test',requestId:'req_memory'}));const mixed=store.transaction(actor,tx=>tx.skills.resolveRetrieval('Despliega mi proyecto kubernetes como solemos','default',actor.scope,{supportingThreshold:0.3}));expect(mixed.policy.memoryRetrievalRequired).toBe(true);expect(mixed.memories).toHaveLength(1);expect(mixed.skills.length).toBeGreaterThan(0);const noMatch=store.transaction(actor,tx=>tx.skills.resolveRetrieval('Deploy a COBOL mainframe to an unknown moon token=abc','default',actor.scope,{supportingThreshold:0.99,canonicalThreshold:0.99}));expect(noMatch.noMatch).toBe(true);const {DatabaseSync}=await import('node:sqlite');store.close();const probe=new DatabaseSync(join(roots[0]!,'hub.sqlite'));const events=probe.prepare('SELECT query_redacted,query_sha256,no_match FROM retrieval_events ORDER BY created_at').all() as Array<{query_redacted:string;query_sha256:string;no_match:number}>;expect(events).toHaveLength(3);expect(events.every(e=>/^[0-9a-f]{64}$/u.test(e.query_sha256))).toBe(true);expect(events.some(e=>e.no_match===1)).toBe(true);expect(events.map(e=>e.query_redacted).join(' ')).not.toContain('token=abc');expect(()=>probe.prepare("UPDATE retrieval_events SET profile='tampered'").run()).toThrow();probe.close();}finally{try{store.close();}catch{/* closed */}}});
});
