// packages/mcp/src/generated-tool-metadata.ts
//
// DO NOT EDIT. This file is regenerated by scripts/generate-mcp-tools.mjs
// from openapi/openapi.yaml + schemas/mcp-capabilities.v1.json. Hand-edits
// will be overwritten by the next generator run.

import type { ToolCatalogEntry, GeneratedToolMetadata } from './types.js';

export const GENERATED_TOOLS: readonly ToolCatalogEntry[] = [
  {
    "operationId": "getHealth",
    "capability": "health.read",
    "safety": "safe",
    "rest": {
      "method": "GET",
      "path": "/api/v1/health"
    },
    "cas": false,
    "idempotent": false
  },
  {
    "operationId": "getStatus",
    "capability": "status.read",
    "safety": "safe",
    "rest": {
      "method": "GET",
      "path": "/api/v1/status"
    },
    "cas": false,
    "idempotent": false
  },
  {
    "operationId": "getDoctor",
    "capability": "admin.doctor",
    "safety": "diagnostic",
    "rest": {
      "method": "GET",
      "path": "/api/v1/admin/doctor"
    },
    "cas": false,
    "idempotent": false
  },
  {
    "operationId": "listIdentities",
    "capability": "identity.read",
    "safety": "safe",
    "rest": {
      "method": "GET",
      "path": "/api/v1/identities"
    },
    "cas": false,
    "idempotent": false
  },
  {
    "operationId": "createBinding",
    "capability": "binding.write",
    "safety": "mutating",
    "rest": {
      "method": "POST",
      "path": "/api/v1/bindings"
    },
    "cas": true,
    "idempotent": true
  },
  {
    "operationId": "createProfile",
    "capability": "profile.write",
    "safety": "mutating",
    "rest": {
      "method": "POST",
      "path": "/api/v1/profiles"
    },
    "cas": false,
    "idempotent": true
  },
  {
    "operationId": "listMemoryBlocks",
    "capability": "memory.read",
    "safety": "safe",
    "rest": {
      "method": "GET",
      "path": "/api/v1/memory-blocks"
    },
    "cas": false,
    "idempotent": false
  },
  {
    "operationId": "createEvent",
    "capability": "event.write",
    "safety": "mutating",
    "rest": {
      "method": "POST",
      "path": "/api/v1/events"
    },
    "cas": false,
    "idempotent": true
  },
  {
    "operationId": "createMemory",
    "capability": "memory.write",
    "safety": "mutating",
    "rest": {
      "method": "POST",
      "path": "/api/v1/memories"
    },
    "cas": false,
    "idempotent": true
  },
  {
    "operationId": "supersedeMemory",
    "capability": "memory.supersede",
    "safety": "mutating",
    "rest": {
      "method": "POST",
      "path": "/api/v1/memories/{id}/supersede"
    },
    "cas": true,
    "idempotent": true
  },
  {
    "operationId": "forgetMemory",
    "capability": "memory.forget",
    "safety": "destructive",
    "rest": {
      "method": "POST",
      "path": "/api/v1/memories/{id}/forget"
    },
    "cas": true,
    "idempotent": true
  },
  {
    "operationId": "listSkills",
    "capability": "skill.read",
    "safety": "safe",
    "rest": {
      "method": "GET",
      "path": "/api/v1/skills"
    },
    "cas": false,
    "idempotent": false
  },
  {
    "operationId": "listSkillVersions",
    "capability": "skill.version.read",
    "safety": "safe",
    "rest": {
      "method": "GET",
      "path": "/api/v1/skills/{id}/versions"
    },
    "cas": false,
    "idempotent": false
  },
  {
    "operationId": "getResource",
    "capability": "resource.read",
    "safety": "safe",
    "rest": {
      "method": "GET",
      "path": "/api/v1/resources/{path}"
    },
    "cas": false,
    "idempotent": false
  },
  {
    "operationId": "getCatalog",
    "capability": "catalog.read",
    "safety": "safe",
    "rest": {
      "method": "GET",
      "path": "/api/v1/catalog"
    },
    "cas": false,
    "idempotent": false
  },
  {
    "operationId": "previewCatalogSync",
    "capability": "catalog.sync.preview",
    "safety": "mutating",
    "rest": {
      "method": "POST",
      "path": "/api/v1/catalog/sync/preview"
    },
    "cas": false,
    "idempotent": true
  },
  {
    "operationId": "applyCatalogSync",
    "capability": "catalog.sync.apply",
    "safety": "mutating",
    "rest": {
      "method": "POST",
      "path": "/api/v1/catalog/sync/apply"
    },
    "cas": true,
    "idempotent": true
  },
  {
    "operationId": "listAudit",
    "capability": "audit.read",
    "safety": "safe",
    "rest": {
      "method": "GET",
      "path": "/api/v1/audit"
    },
    "cas": false,
    "idempotent": false
  },
  {
    "operationId": "listSnapshots",
    "capability": "snapshot.read",
    "safety": "safe",
    "rest": {
      "method": "GET",
      "path": "/api/v1/snapshots"
    },
    "cas": false,
    "idempotent": false
  },
  {
    "operationId": "replay",
    "capability": "replay.run",
    "safety": "diagnostic",
    "rest": {
      "method": "POST",
      "path": "/api/v1/replay"
    },
    "cas": false,
    "idempotent": true
  },
  {
    "operationId": "previewMaterialization",
    "capability": "materialization.preview",
    "safety": "safe",
    "rest": {
      "method": "POST",
      "path": "/api/v1/materializations/preview"
    },
    "cas": false,
    "idempotent": true
  },
  {
    "operationId": "applyMaterialization",
    "capability": "materialization.apply",
    "safety": "mutating",
    "rest": {
      "method": "POST",
      "path": "/api/v1/materializations/apply"
    },
    "cas": true,
    "idempotent": true
  },
  {
    "operationId": "rollbackMaterialization",
    "capability": "materialization.rollback",
    "safety": "destructive",
    "rest": {
      "method": "POST",
      "path": "/api/v1/materializations/{run_id}/rollback"
    },
    "cas": true,
    "idempotent": true
  }
];

export const GENERATED_METADATA: GeneratedToolMetadata = Object.freeze({
  generator: "@portable-agent-asset-hub/mcp/generate-mcp-tools",
  version: "0.1.0",
  source: "openapi/openapi.yaml",
  generatedAt: "2026-08-21T14:07:36.844Z",
  capabilityMatrix: "schemas/mcp-capabilities.v1.json",
  operationCount: GENERATED_TOOLS.length,
  tools: GENERATED_TOOLS as ToolCatalogEntry[],
});
