import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { createHash } from 'node:crypto';
import { mkdir, writeFile, readFile } from 'node:fs/promises';
import { join, resolve } from 'node:path';
const exec=promisify(execFile),root=resolve(new URL('..',import.meta.url).pathname),out=join(root,'artifacts/s5-evidence.json');
const names=['lint','typecheck','build','targeted-s5','full-tests','owner-scan','fresh-process','package-reproducibility','external-install','audit','s4-regression'];
const s5Tests=['tests/s5-catalog.test.ts','tests/s5-real.test.ts','tests/s5-adversarial.test.ts','tests/s5-coordinator.test.ts'];
const normative=['logical_key_stable','preview_digest_deterministic','apply_requires_reviewed_digest','apply_rejects_expired_preview','apply_rejects_all_drift_classes','replayed_apply_is_noop','partial_selector_does_not_stale_excluded_entries','symlink_root_and_escape_rejected','failure_rolls_back_entries_sources_audit_and_marker','relations_require_same_scope'];
const steps=Object.fromEntries(names.map(n=>[n,{status:'PENDING'}])); const digest=x=>createHash('sha256').update(x).digest('hex');
async function persist(status='RUNNING',assertionCount=0){await mkdir(join(root,'artifacts'),{recursive:true});await writeFile(out,JSON.stringify({gate:'s5',status,complete:false,assertionCount,steps,limits:{rawBodiesCaptured:false}},null,2)+'\n');}
await persist('PENDING');
async function run(name,file,args){const startedAt=new Date().toISOString();try{const r=await exec(file,args,{cwd:root,env:{...process.env,CI:'true'},maxBuffer:60*1024*1024});steps[name]={status:'PASS',exitCode:0,startedAt,stdoutDigest:digest(r.stdout),stderrDigest:digest(r.stderr)};return true;}catch(e){steps[name]={status:'FAIL',exitCode:Number(e.code??1),startedAt,stdoutDigest:digest(e.stdout??''),stderrDigest:digest(e.stderr??String(e))};return false;}finally{await persist();}}
let ok=true;for(const [name,file,args] of [['lint','pnpm',['lint']],['typecheck','pnpm',['typecheck']],['build','pnpm',['build']]]){if(!(ok=await run(name,file,args)))break;}
let assertionCount=0;if(ok){ok=await run('targeted-s5','pnpm',['exec','vitest','run',...s5Tests,'--reporter=json','--outputFile=artifacts/s5-targeted.json']);try{const r=JSON.parse(await readFile(join(root,'artifacts/s5-targeted.json'),'utf8'));assertionCount=Number(r.numTotalTests);steps['targeted-s5'].assertionCount=assertionCount;const namesFound=(r.testResults??[]).flatMap((file)=>file.assertionResults??[]).map((test)=>test.fullName??test.title??'').join('\n');if(assertionCount<10||normative.some((name)=>!namesFound.includes(name)))throw new Error('targeted S5 assertions or normative names missing');}catch(e){steps['targeted-s5'].status='FAIL';steps['targeted-s5'].error=String(e);ok=false;}}
for(const [name,file,args] of [['full-tests','pnpm',['test']],['owner-scan',process.execPath,['scripts/scan-sqlite-owner.mjs']],['fresh-process',process.execPath,['scripts/s5-fresh-process.mjs']],['package-reproducibility',process.execPath,['scripts/package-repro.mjs']],['external-install',process.execPath,['scripts/external-install-s5.mjs']],['audit','pnpm',['audit','--prod']],['s4-regression','pnpm',['s4:gate']]]){if(!ok)break;ok=await run(name,file,args);}
const complete=ok&&names.every(n=>steps[n].status==='PASS')&&assertionCount>=10;const artifact={gate:'s5',status:complete?'PASS':'FAIL',complete,assertionCount,steps,limits:{rawBodiesCaptured:false}};await writeFile(out,JSON.stringify(artifact,null,2)+'\n');console.log(JSON.stringify(artifact));if(!complete)process.exitCode=1;
